// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aygeapgtqifyogkgzjre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Z2VhcGd0cWlmeW9na2d6anJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDkxMzYsImV4cCI6MjA2NDg4NTEzNn0.UCvVdGF4PoHxy2AlWHyZhBWS8RHMNDzvlwMYXVf6YjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);